language: node_js
sudo: required

node_js:
  - '14'

cache:
  npm: false
  yarn: false

jobs:
  fast_finish: true
  include:
    - stage: Building scripts
      # No installs are needed but we need to be sure that 
      install: yarn install
      script:
        - yarn lint
        - yarn build
        - yarn test
      deploy:
        provider: pages
        local_dir: docs/build
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: true
        on:
          branch: master
