language: node_js
sudo: required

node_js:
  - '14'

cache:
  npm: false
  yarn: false

jobs:
  fast_finish: true
  include:
    - stage: Building scripts
      # No installs are needed but we need to be sure that 
      install: yarn install
      script:
        - yarn lint
        - yarn build
        - yarn test
