name: CI-CD
on:
  push:
  pull_request:

jobs:
  build:
    name: Lint, build and test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: yarn
      - run: yarn install --immutable
      - run: yarn lint
      - run: yarn build
      - run: yarn test
  deploy:
    name: Deploy on github pages
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      pages: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: yarn
      - run: yarn install --immutable
      - run: yarn build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445  # v4.9.0
        with:
          branch: gh-pages
          folder: docs/build
