name: CI

on: push

jobs:
  build:
    name: Lint, build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup yarn cache
        uses: c-hive/gha-yarn-cache@v2
      - name: Setup NodeJS 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn lint
      - run: yarn build
      - run: yarn test
